// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8U9mNCimWndXLb6Sb_HWS8u3N5mkZUbY',
    appId: '1:286323631195:web:9fdf630ab256636933cb7e',
    messagingSenderId: '286323631195',
    projectId: 'fyp-civic-connect',
    authDomain: 'fyp-civic-connect.firebaseapp.com',
    storageBucket: 'fyp-civic-connect.firebasestorage.app',
    measurementId: 'G-Y4PVXDRKSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAshgHJmUFljQVQboEQ7LxuZK7c6m1q7Z4',
    appId: '1:286323631195:android:74950fdf0e0c140a33cb7e',
    messagingSenderId: '286323631195',
    projectId: 'fyp-civic-connect',
    storageBucket: 'fyp-civic-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9X2-Tg4PUwToEnaVL3-F6AiS630NjZPM',
    appId: '1:286323631195:ios:f5c9b3758ed4777f33cb7e',
    messagingSenderId: '286323631195',
    projectId: 'fyp-civic-connect',
    storageBucket: 'fyp-civic-connect.firebasestorage.app',
    iosBundleId: 'com.example.fypCivicConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9X2-Tg4PUwToEnaVL3-F6AiS630NjZPM',
    appId: '1:286323631195:ios:f5c9b3758ed4777f33cb7e',
    messagingSenderId: '286323631195',
    projectId: 'fyp-civic-connect',
    storageBucket: 'fyp-civic-connect.firebasestorage.app',
    iosBundleId: 'com.example.fypCivicConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8U9mNCimWndXLb6Sb_HWS8u3N5mkZUbY',
    appId: '1:286323631195:web:a3a44f7d5456659833cb7e',
    messagingSenderId: '286323631195',
    projectId: 'fyp-civic-connect',
    authDomain: 'fyp-civic-connect.firebaseapp.com',
    storageBucket: 'fyp-civic-connect.firebasestorage.app',
    measurementId: 'G-HYHWX7BGM1',
  );
}
